; ============================================================================
; FLOWWHEEL - MULTI-LANGUAGE SYSTEM
; ============================================================================

; --- LƯU Ý ĐÓNG GÓI TÀI NGUYÊN ---
; AutoHotkey v2 KHÔNG hỗ trợ FileInstall. Khi biên dịch, hãy copy các file tài nguyên (FlowWheelSoundFeedback.wav, flowwheel.ini, mouse_guide.png, QR.png, FlowWheel.ico, FlowWheel.png, Thumbnail.png)
; vào cùng thư mục với file .exe để chương trình hoạt động đầy đủ.

; --- PLAY GESTURE SOUND FEEDBACK ---
PlayGestureSound() {
    global cfg
    if !cfg.feedback.HasOwnProp("soundEnabled") || !cfg.feedback.soundEnabled
        return
    ; Phát âm thanh nhẹ nhàng từ file nếu có
    ; Kiểm tra trong thư mục script hoặc thư mục làm việc
    soundFile := A_ScriptDir . "\..\resources\sounds\FlowWheelSoundFeedback.wav"
    if !FileExist(soundFile)
        soundFile := A_ScriptDir . "\..\resources\FlowWheelSoundFeedback.wav" ; Legacy path
    if FileExist(soundFile)
        SoundPlay soundFile, "wait"
    else
        SoundBeep 1000, 80 ; fallback nếu không tìm thấy file
}

; --- HỆ THỐNG ĐA NGÔN NGỮ ---
global LANG_MAP := Map(
    "vi", Map(
        ; Gestures & Actions
        "❌ Đã đóng ứng dụng (Alt+Tab)", "❌ Đã đóng ứng dụng (Alt+Tab)",
        "❌ Đã đóng ứng dụng (Tab)", "❌ Đã đóng ứng dụng (Tab)",
        "❌ Đã đóng tab trình duyệt", "❌ Đã đóng tab trình duyệt",
        "♻️ Đã khôi phục tab vừa đóng", "♻️ Đã khôi phục tab vừa đóng",
        "❌ Đã đóng cửa sổ", "❌ Đã đóng cửa sổ",
        "💻 Show/Hide Desktop: Ẩn/Hiện Desktop", "💻 Show/Hide Desktop: Ẩn/Hiện Desktop",
        "🔇 Đã bật/tắt tiếng hệ thống", "🔇 Đã bật/tắt tiếng hệ thống",
        "📸 Đã chụp màn hình!", "📸 Đã chụp màn hình!",
        "⬅️ Đã ghim cửa sổ sang trái", "⬅️ Đã ghim cửa sổ sang trái",
        "➡️ Đã ghim cửa sổ sang phải", "➡️ Đã ghim cửa sổ sang phải",
        "❌ Đóng window từ Taskbar (hover thumbnail)", "❌ Đóng window từ Taskbar (hover thumbnail)",
        "❌ Đóng window từ Taskbar", "❌ Đóng window từ Taskbar",
        "🔍 Phóng to", "🔍 Phóng to",
        "🔍 Thu nhỏ", "🔍 Thu nhỏ",
        "🔄 Chuyển cửa sổ tiếp theo", "🔄 Chuyển cửa sổ tiếp theo",
        "🔄 Chuyển cửa sổ trước", "🔄 Chuyển cửa sổ trước",
        "🔄 Chuyển tab tiếp theo", "🔄 Chuyển tab tiếp theo",
        "🔄 Chuyển tab trước", "🔄 Chuyển tab trước",
        "🔳 Đang chọn taskbar (phải)", "🔳 Đang chọn taskbar (phải)",
        "🔳 Đang chọn taskbar (trái)", "🔳 Đang chọn taskbar (trái)",
        "☀️ Độ sáng", "☀️ Độ sáng",
        "⚠️ Không thể điều chỉnh độ sáng!", "⚠️ Không thể điều chỉnh độ sáng!",
        "🔊 Âm lượng", "🔊 Âm lượng",
        "↔️ Cuộn sang phải", "↔️ Cuộn sang phải",
        "↔️ Cuộn sang trái", "↔️ Cuộn sang trái",
        
        ; UI - Tray Guide
        "FlowWheel đang chạy ở khay hệ thống 🔔", "FlowWheel đang chạy ở khay hệ thống 🔔",
        "Nhấn vào mũi tên ^ ở khay hệ thống để xem biểu tượng", "Nhấn vào mũi tên ^ ở khay hệ thống để xem biểu tượng",
        
        
        ; UI - Settings
        "⚙️ Cài đặt", "⚙️ Cài đặt",
        "Cử chỉ", "Cử chỉ",
        "Hiển thị", "Hiển thị",
        "Nâng cao", "Nâng cao",
        "☕ Hỗ trợ", "☕ Hỗ trợ",
        "🌐 Trình duyệt_Cuộn", "🌐 Browser_Scroll",
        "Chuyển Tab (RButton + Wheel)", "Chuyển Tab (RButton + Wheel)",
        "Đóng Tab nhanh (RButton + MButton)", "Đóng Tab nhanh (RButton + MButton)",
        "Khôi phục Tab (LButton + MButton)", "Khôi phục Tab (LButton + MButton)",
        "Cuộn ngang (Wheel L/R)", "Cuộn ngang (Wheel L/R)",
        "🎵 Giải trí_Media", "🎵 Entertainment_Media",
        "Âm lượng (RButton + X1 + Wheel)", "Âm lượng (RButton + X1 + Wheel)",
        "Độ sáng (RButton + X2 + Wheel)", "Độ sáng (RButton + X2 + Wheel)",
        "Tắt/Bật âm (MButton Click (Nhấn giữ) )", "Tắt/Bật âm (MButton Click (Nhấn giữ) )",
        "Phóng to/Thu nhỏ (MButton + Wheel)", "Phóng to/Thu nhỏ (MButton + Wheel)",
        "🖥️ Hệ thống_Cửa sổ", "🖥️ System _Window",
        "Chuyển/Đóng cửa sổ(X1+Wheel/+RButton)", "Chuyển/Đóng cửa sổ(X1+Wheel/+RButton)",
        "App Taskbar (X2 + Wheel)", "App Taskbar (X2 + Wheel)",
        "Đóng cửa sổ (X1 + MButton)", "Đóng cửa sổ (X1 + MButton)",
        "Show/Hide Desktop (X2 + MButton)", "Show/Hide Desktop (X2 + MButton)",
        "🛠️ Công cụ_Tiện ích", "🛠️ Công cụ _Tiện ích",
        "Chụp màn hình (X1 + X2)", "Chụp màn hình (X1 + X2)",
        "Ghim cửa sổ (RButton + X1/X2)", "Ghim cửa sổ (RButton + X1/X2)",
        "Đóng app trên Taskbar (X1 click)", "Đóng app trên Taskbar (X1 click)",
        "⚠️ Một số tính năng có thể yêu cầu quyền Quản trị viên để hoạt động trên mọi cửa sổ.", "⚠️ Một số tính năng có thể yêu cầu quyền Quản trị viên để hoạt động trên mọi cửa sổ.",
        "Phản hồi trực quan", "Phản hồi trực quan",
        " Hiển thị phản hồi khi thao tác", " Hiển thị phản hồi khi thao tác",
        " Âm thanh phản hổi khi thao tác ", " Âm thanh phản hổi khi thao tác ",
        "🔊 Nghe thử", "🔊 Nghe thử",
        "Thời gian hiển thị:", "Thời gian hiển thị:",
        "mili giây", "mili giây",
        "Vị trí:", "Vị trí:",
        "Gần con trỏ", "Gần con trỏ",
        "Giữa màn hình", "Giữa màn hình",
        "Góc trên bên phải", "Góc trên bên phải",
        "👁️ Xem thử hiển thị", "👁️ Xem thử hiển thị",
        "Hệ thống / Hành vi", "Hệ thống / Hành vi",
        "Khởi động cùng Windows", "Khởi động cùng Windows",
        "Hiện màn hình chào mừng khi khởi động", "Hiện màn hình chào mừng khi khởi động",
        "Hiệu năng / Độ nhạy", "Hiệu năng / Độ nhạy",
        "Bước tăng âm lượng:", "Bước tăng âm lượng:",
        "Bước tăng độ sáng:", "Bước tăng độ sáng:",
        "Thời gian giữ nút giữa để tắt/bật volume (ms):", "Thời gian giữ nút giữa để tắt/bật volume (ms):",
        "Gia tốc cuộn:", "Gia tốc cuộn:",
        "Tắt", "Tắt",
        "Thấp(x2)", "Thấp(x2)",
        "TB(x3)", "TB(x3)",
        "Cao(x5)", "Cao(x5)",
        "Max(x8)", "Max(x8)",
        "Bật chế độ gỡ lỗi cho nhà phát triển", "Bật chế độ gỡ lỗi cho nhà phát triển",
        "Bảo trì", "Bảo trì",
        "📁 Mở thư mục cấu hình", "📁 Mở thư mục cấu hình",
        "📤 Xuất cấu hình", "📤 Xuất cấu hình",
        "📥 Nhập cấu hình", "📥 Nhập cấu hình",
        "🚀 Góp ý & Báo lỗi", "🚀 Góp ý & Báo lỗi",
        "FlowWheel Settings", "Cài đặt FlowWheel",
        "Share your feedback", "Chia sẻ phản hồi của bạn",
        "Your input helps us improve FlowWheel", "Ý kiến của bạn giúp chúng tôi cải thiện FlowWheel",
        "📎 Attach", "📎 Đính kèm",
        "🗑️ Clear", "🗑️ Xóa",
        "What type of feedback is this?", "Đây là loại phản hồi nào?",
        "🐛 Bug", "🐛 Lỗi",
        "💡 Idea", "💡 Ý tưởng",
        "❓ Question", "❓ Câu hỏi",
        "💬 Other", "💬 Khác",
        "How would you rate your experience?", "Bạn đánh giá trải nghiệm của mình thế nào?",
        "😞 Needs improvement", "😞 Cần cải thiện",
        "😕 Could be better", "😕 Có thể tốt hơn",
        "😐 Okay", "😐 Ổn",
        "😊 Good", "😊 Tốt",
        "😍 Excellent!", "😍 Tuyệt vời!",
        "Submit feedback", "Gửi phản hồi",
        "Sent: ", "Đã gửi: ",
        "Contact info (optional)", "Thông tin liên hệ (không bắt buộc)",
        "your.email@example.com", "email.cua.ban@vi-du.com",
        "Join our community", "Tham gia cộng đồng của chúng tôi",
        "🔗 Discord Server  →", "🔗 Máy chủ Discord  →",
        "FAQ", "Các câu hỏi thường gặp",
        "Donate", "Ủng hộ",
        "Changelog", "Nhật ký thay đổi",
        "GitHub", "GitHub",
        "Reset defaults", "Khôi phục cài đặt gốc",
        "Apply & Save", "Áp dụng & Lưu",
        "Cancel", "Hủy bỏ",
        
        
        ; UI - Stats
        "Thống kê FlowWheel", "Thống kê FlowWheel",
        "📊 Thống kê sử dụng", "📊 Thống kê sử dụng",
        "Tổng số cử chỉ đã thực hiện", "Tổng số cử chỉ đã thực hiện",
        "Hạng: ", "Hạng: ",
        "⏱️ Thời gian tiết kiệm được so với thao tác thủ công cũ: ", "⏱️ Thời gian tiết kiệm được so với thao tác thủ công cũ: ",
        "🏆 Cử chỉ dùng nhiều nhất", "🏆 Cử chỉ dùng nhiều nhất",
        " lần", " lần",
        "Phân tích chi tiết", "Phân tích chi tiết",
        "Chưa có dữ liệu cử chỉ nào.", "Chưa có dữ liệu cử chỉ nào.",
        "🏆 Khoe thành tích & Hạng lên Discord", "🏆 Khoe thành tích & Hạng lên Discord",
        "🗑️ Xóa thống kê", "🗑️ Xóa thống kê",
        "✓ Đóng", "✓ Đóng",
        "Bạn có chắc muốn xóa toàn bộ thống kê?", "Bạn có chắc muốn xóa toàn bộ thống kê?",
        "Xác nhận", "Xác nhận",
        "✓ Đã xóa thống kê", "✓ Đã xóa thống kê",
        
        ; UI - About
        "Giới thiệu về FlowWheel", "Giới thiệu về FlowWheel",
        "Chuyển động nhỏ - Dòng chảy lớn", "Chuyển động nhỏ - Dòng chảy lớn",
        "Được sáng tạo và phát triển bởi", "Được sáng tạo và phát triển bởi",
        "Truy cập nhanh", "Truy cập nhanh",
        "Ctrl + Alt + S  →  Cài đặt", "Ctrl + Alt + S  →  Cài đặt",
        "Ctrl + Alt + H  →  Tham khảo nhanh", "Ctrl + Alt + H  →  Tham khảo nhanh",
        "Ctrl + Alt + Q  →  Thoát ứng dụng", "Ctrl + Alt + Q  →  Thoát ứng dụng",
        "Ctrl + Alt + P  →  Tạm dừng chức năng", "Ctrl + Alt + P  →  Tạm dừng chức năng",
        "Ctrl + Alt + R  →  Tải lại script", "Ctrl + Alt + R  →  Tải lại script",
        "☕ Ủng hộ phát triển", "☕ Ủng hộ phát triển",
        "(Không tìm thấy QR.png)", "(Không tìm thấy QR.png)",
        "Mời tác giả một ly cà phê ☕", "Mời tác giả một ly cà phê ☕",
        "© 2026 Minh Edward. ", "© 2026 Minh Edward. ",
        "Đóng", "Đóng",
        
        ; UI - Tray Menu
        "FlowWheel ", "FlowWheel ",
        "⚙️ Cài đặt`tCtrl+Alt+S", "⚙️ Cài đặt`tCtrl+Alt+S",
        "📋 Tham khảo nhanh`tCtrl+Alt+H", "📋 Tham khảo nhanh`tCtrl+Alt+H",
        "📊 Thống kê", "📊 Thống kê",
        "⏱️ Thời gian tiết kiệm : ", "⏱️ Thời gian tiết kiệm : ",
        "🎨 Phản hồi trực quan: ", "🎨 Phản hồi trực quan: ",
        "Bật", "Bật",
        "Tắt", "Tắt",
        "⏸️ Tạm dừng FlowWheel`tCtrl+Alt+P", "⏸️ Tạm dừng FlowWheel`tCtrl+Alt+P",
        "🔄 Tải lại script`tCtrl+Alt+R", "🔄 Tải lại script`tCtrl+Alt+R",
        "❌ Thoát`tCtrl+Alt+Q", "❌ Thoát`tCtrl+Alt+Q",
        "✓ Đã bật phản hồi trực quan", "✓ Đã bật phản hồi trực quan",
        "✗ Đã tắt phản hồi trực quan", "✗ Đã tắt phản hồi trực quan",
        
        ; UI - Welcome
        "👋 Chào mừng đến với FlowWheel", "👋 Welcome to FLowWheel",
        "Thao tác chuột mạnh mẽ cho Windows 10/11", "Thao tác chuột mạnh mẽ cho Windows 10/11",
        "FlowWheel giúp chuột của bạn mạnh mẽ hơn với các cử chỉ thông minh, tăng tốc làm việc và điều khiển Windows dễ dàng.", "FlowWheel giúp chuột của bạn mạnh mẽ hơn với các cử chỉ thông minh, tăng tốc làm việc và điều khiển Windows dễ dàng.",
        "⚠️ Yêu cầu phần cứng", "⚠️ Yêu cầu phần cứng",
        "Cần chuột có 2 nút bên hông (XButton1/XButton2).", "Cần chuột có 2 nút bên hông (XButton1/XButton2).",
        "🚀 Bắt đầu nhanh", "🚀 Bắt đầu nhanh",
        "Hãy thử: Giữ CHUỘT PHẢI + cuộn để ", "Hãy thử: Giữ CHUỘT PHẢI + cuộn để ",
        "chuyển tab trình duyệt", "chuyển tab trình duyệt",
        " ngay lập tức!", " ngay lập tức!",
        "Nhấn Ctrl+Alt+H bất cứ lúc nào để xem hướng dẫn cử chỉ", "Nhấn Ctrl+Alt+H bất cứ lúc nào để xem hướng dẫn cử chỉ",
        "Không hiển thị màn hình chào mừng này nữa", "Không hiển thị màn hình chào mừng này nữa",
        "📖 Học cách dùng", "📖 Learn to use",
        "✓ Bắt đầu sử dụng", "✓ Bắt đầu sử dụng",
        
        ; Misc
        "Hiển thị", "Hiển thị",
        "✓ Cài đặt đã được áp dụng!", "✓ Cài đặt đã được áp dụng!",
        "Ngôn ngữ / Language:", "Ngôn ngữ / Language:",
        "Ngôn ngữ đã thay đổi!", "Ngôn ngữ đã thay đổi!",
        "🌐 Ngôn ngữ / Language:", "🌐 Ngôn ngữ / Language:",
        ; UI - Support/Info (supplement)
        "Ví dụ: MinhEdward#1234 hoặc Email...", "E.g.: MinhEdward#1234 or Email...",
        "Câu hỏi thường gặp", "Frequently Asked Questions",
        "Có gì mới?", "What's new?",
        "Ủng hộ dự án", "support the project",
        "Bạn muốn đóng góp phát triển mã nguồn ? click vào đây", "Want to contribute to the development of the source code? Click here",
        ; Config Errors
        "Error loading config", "Lỗi tải cấu hình",
        "Error saving config", "Lỗi lưu cấu hình",
        "Config Error", "Lỗi cấu hình"
    ),
    "en", Map(
        ; Gestures & Actions
        "❌ Đã đóng ứng dụng (Alt+Tab)", "❌ Closed app (Alt+Tab)",
        "❌ Đã đóng ứng dụng (Tab)", "❌ Closed app (Tab)",
        "❌ Đã đóng tab trình duyệt", "❌ Closed browser tab",
        "♻️ Đã khôi phục tab vừa đóng", "♻️ Restored closed tab",
        "❌ Đã đóng cửa sổ", "❌ Closed window",
        "💻 Show/Hide Desktop: Ẩn/Hiện Desktop", "💻 Show/Hide Desktop: Show/Hide Desktop",
        "🔇 Đã bật/tắt tiếng hệ thống", "🔇 System mute toggled",
        "📸 Đã chụp màn hình!", "📸 Screenshot captured!",
        "⬅️ Đã ghim cửa sổ sang trái", "⬅️ Window snapped left",
        "➡️ Đã ghim cửa sổ sang phải", "➡️ Window snapped right",
        "❌ Đóng window từ Taskbar (hover thumbnail)", "❌ Close window from Taskbar (hover thumbnail)",
        "❌ Đóng window từ Taskbar", "❌ Close window from Taskbar",
        "🔍 Phóng to", "🔍 Zoom in",
        "🔍 Thu nhỏ", "🔍 Zoom out",
        "🔄 Chuyển cửa sổ tiếp theo", "🔄 Switch to next window",
        "🔄 Chuyển cửa sổ trước", "🔄 Switch to previous window",
        "🔄 Chuyển tab tiếp theo", "🔄 Switch to next tab",
        "🔄 Chuyển tab trước", "🔄 Switch to previous tab",
        "🔳 Đang chọn taskbar (phải)", "🔳 Taskbar selection (right)",
        "🔳 Đang chọn taskbar (trái)", "🔳 Taskbar selection (left)",
        "☀️ Độ sáng", "☀️ Brightness",
        "⚠️ Không thể điều chỉnh độ sáng!", "⚠️ Cannot adjust brightness!",
        "🔊 Âm lượng", "🔊 Volume",
        "↔️ Cuộn sang phải", "↔️ Scroll right",
        "↔️ Cuộn sang trái", "↔️ Scroll left",
        
        ; UI - Tray Guide
        "FlowWheel đang chạy ở khay hệ thống 🔔", "FlowWheel is running in system tray 🔔",
        "Nhấn vào mũi tên ^ ở khay hệ thống để xem biểu tượng", "Click the arrow ^ in the system tray to see the icon",
        
        ; UI - Gesture Guide
        "FlowWheel", "FlowWheel",
        "Bảng Tham Khảo Nhanh", "Quick Reference Guide",
        "Nhấn để mở cài đặt", "Open settings",
        "🖱️ Cấu Hình Thiết Bị", "🖱️ Hardware Setup",
        "Tối ưu cho chuột 5 nút", "Optimized for 5-button mouse",
        "🌐Điều hướng Web / Trình duyệt", "🌐Web / Browser Navigation",
        "Chuyển Tab trình `n duyệt", "Switch Browser `n Tabs",
        "Đóng Tab nhanh", "Close Tab quickly",
        "Khôi phục Tab đã `n đóng", "Restore Closed `n Tab",
        "Cuộn ngang (Tilt wheel)", "Horizontal scroll (Tilt wheel)",
        "🖥️Quản lý Cửa sổ / Hệ thống", "🖥️Window / System Management",
        "Chuyển / đóng cửa `n sổ (Alt+Tab)", "Switch / close `n windows (Alt+Tab)",
        "Chọn ứng dụng Taskbar", "Select Taskbar app",
        "Đóng cửa sổ nhanh", "Close window quickly",
        "Show/Hide Desktop", "Show/Hide Desktop",
        "🎵Điều khiển Đa phương tiện", "🎵Multimedia Control",
        "Điều chỉnh âm lượng", "Adjust volume",
        "Điều chỉnh độ sáng", "Adjust brightness",
        "Bật/Tắt âm thanh (Mute)", "Toggle mute",
        "Phóng to / Thu nhỏ (Zoom)", "Zoom in/out",
        "🛠️Tiện ích / Nâng cao", "🛠️Utilities / Advanced",
        "Chụp màn hình nhanh", "Quick screenshot",
        "Ghim cửa sổ (Snap)", "Snap window",
        "Đóng ứng dụng từ Taskbar", "Close app from Taskbar",
        "⚡ Truy cập nhanh", "⚡ Quick Access",
        "Cài đặt", "Settings",
        "Hướng dẫn", "Guide",
        "Thoát", "Exit",
        "Tạm dừng", "Pause",
        "Tải lại", "Reload",
        "💡 Hãy vào Cài đặt để tùy chỉnh cử chỉ theo ý bạn!", "💡 Go to Settings to customize gestures!",
        "Nhấn Ctrl+Alt+H bất cứ lúc nào để mở lại hướng dẫn này", "Press Ctrl+Alt+H anytime to open this guide",
        "✓ ĐÃ HIỂU!", "✓ GOT IT!",
        
        ; UI - Settings
        "⚙️ Cài đặt", "⚙️ Settings",
        "Cử chỉ", "Gestures",
        "Hiển thị", "Display",
        "Nâng cao", "Advanced",
        "☕ Hỗ trợ", "☕ Support",
        ; UI - Tab Titles (explicit)
        "🎯 Cử chỉ", "🎯 Gestures",
        "🎨 Hiển thị", "🎨 Display",
        "⚙️ Nâng cao", "⚙️ Advanced",
        "💬 Hỗ trợ", "💬 Support",
        ; UI - Settings Management/Customization
        "🔧 Hệ thống / Hành vi", "🔧 System / Behavior",
        "⚡ Hiệu năng / Độ nhạy", "⚡ Performance / Sensitivity",
        "🐛 Bật chế độ gỡ lỗi cho nhà phát triển", "🐛 Enable debug mode for developers",
        "🗂️ Bảo trì", "🗂️ Maintenance",
        "💬 Hỗ trợ", "💬 Support",
        "❓ Hỗ trợ & Tài nguyên", "❓ Support & Resources",
        "Đóng góp mã nguồn", "Contribute source code",
        "Quản lý và tùy chỉnh trải nghiệm FlowWheel của bạn", "Manage and customize your FlowWheel experience",
        "🌐 Trình duyệt_Cuộn", "🌐 Browse _Scroll",
        "Chuyển Tab (RButton + Wheel)", "Switch Tabs (RButton + Wheel)",
        "Đóng Tab nhanh (RButton + MButton)", "Quick Close Tab (RButton + MButton)",
        "Khôi phục Tab (LButton + MButton)", "Restore Tab (LButton + MButton)",
        "Cuộn ngang (Wheel L/R)", "Horizontal Scroll (Wheel L/R)",
        "🎵 Giải trí_Media", "🎵 Entertainment_Media",
        "Âm lượng (RButton + X1 + Wheel)", "Volume (RButton + X1 + Wheel)",
        "Độ sáng (RButton + X2 + Wheel)", "Brightness (RButton + X2 + Wheel)",
        "Tắt/Bật âm (MButton Click (Nhấn giữ) )", "Mute Toggle (MButton Press & Hold)",
        "Phóng to/Thu nhỏ (MButton + Wheel)", "Zoom (MButton + Wheel)",
        "🖥️ Hệ thống_Cửa sổ", "🖥️ System_Window",
        "Chuyển/Đóng cửa sổ(X1+Wheel/+RButton)", "Switch/Close window (X1+Wheel/+RButton)",
        "App Taskbar (X2 + Wheel)", "Taskbar App (X2 + Wheel)",
        "Đóng cửa sổ (X1 + MButton)", "Close Window (X1 + MButton)",
        "Ẩn/Hiện Desktop (X2 + MButton)", "Show/Hide Desktop (X2 + MButton)",
        "🛠️ Công cụ_Tiện ích", "🛠️ Tools_Utilities",
        "Chụp màn hình (X1 + X2)", "Screenshot (X1 + X2)",
        "Ghim cửa sổ (RButton + X1/X2)", "Snap Window (RButton + X1/X2)",
        "Đóng app trên Taskbar (X1 click)", "Close app on Taskbar (X1 click)",
        "⚠️ Một số tính năng có thể yêu cầu quyền Quản trị viên để hoạt động trên mọi cửa sổ.", "⚠️ Some features may require Administrator rights to work on all windows.",
        "Phản hồi trực quan", "Visual Feedback",
        " Hiển thị phản hồi khi thao tác", " Show visual feedback on actions",
        "Âm thanh phản hồi", "Sound feedback",
        "🔧 Hệ thống / Hành vi", "🔧 System / Behavior",
        "🔊 Nghe thử", "🔊 Test Sound",
        "Thời gian hiển thị:", "Display duration:",
        "mili giây", "milliseconds",
        "Vị trí:", "Position:",
        "Gần con trỏ", "Near cursor",
        "Giữa màn hình", "Center screen",
        "Góc trên bên phải", "Top right corner",
        "👁️ Xem thử hiển thị", "👁️ Preview display",
        "Hệ thống / Hành vi", "System / Behavior",
        "Khởi động cùng Windows", "Start with Windows",
        "Hiện màn hình chào mừng khi khởi động", "Show welcome screen on startup",
        "Hiệu năng / Độ nhạy", "Performance / Sensitivity",
        "Bước tăng âm lượng:", "Volume step:",
        "Bước tăng độ sáng:", "Brightness step:",
        "Thời gian giữ nút giữa để tắt/bật volume (ms):", "Middle button hold time for mute (ms):",
        "Gia tốc cuộn:", "Scroll acceleration:",
        "Tắt", "Off",
        "Thấp(x2)", "Low(x2)",
        "TB(x3)", "Med(x3)",
        "Cao(x5)", "High(x5)",
        "Max(x8)", "Max(x8)",
        "Bật chế độ gỡ lỗi cho nhà phát triển", "Enable debug mode for developers",
        "Bảo trì", "Maintenance",
        "📁 Mở thư mục cấu hình", "📁 Open config folder",
        "📤 Xuất cấu hình", "📤 Export config",
        "📥 Nhập cấu hình", "📥 Import config",
        "🚀 Góp ý & Báo lỗi", "🚀 Feedback & Bug Report",
        "Tên/Liên hệ (Tùy chọn):", "Name/Contact (Optional):",
        "Nội dung phản hồi:", "Feedback content:",
        "Danh mục:", "Category:",
        "Đánh giá:", "Rating:",
        "📎 Đính kèm file", "📎 Attach file",
        "🗑️ Xóa", "🗑️ Remove",
        "(Chưa chọn file)", "(No file selected)",
        "📤 Gửi phản hồi", "📤 Send feedback",
        "🔗 Tham gia nhóm Discord", "🔗 Join Discord community",
        "📊 Đã gửi: ", "📊 You sent: ",
        " phản hồi", " feedback",
        "❓ Hỗ trợ / Thông tin", "❓ Support / Info",
        "↺ Đặt lại mặc định", "↺ Reset to defaults",
        "✓ Áp dụng & Lưu", "✓ Apply & Save",
        "✗ Hủy", "✗ Cancel",
        "Bạn có chắc muốn đặt lại tất cả cài đặt về mặc định?", "Are you sure you want to reset all settings to defaults?",
        "Đặt lại cấu hình", "Reset Configuration",
        "✓ Đã đặt lại cài đặt mặc định", "✓ Settings reset to defaults",
        "FlowWheel Settings", "FlowWheel Settings",
        "Share your feedback", "Share your feedback",
        "Your input helps us improve FlowWheel", "Your input helps us improve FlowWheel",
        "📎 Attach", "📎 Attach",
        "🗑️ Clear", "🗑️ Clear",
        "What type of feedback is this?", "What type of feedback is this?",
        "🐛 Bug", "🐛 Bug",
        "💡 Idea", "💡 Idea",
        "❓ Question", "❓ Question",
        "💬 Other", "💬 Other",
        "How would you rate your experience?", "How would you rate your experience?",
        "😞 Needs improvement", "😞 Needs improvement",
        "😕 Could be better", "😕 Could be better",
        "😐 Okay", "😐 Okay",
        "😊 Good", "😊 Good",
        "😍 Excellent!", "😍 Excellent!",
        "Submit feedback", "Submit feedback",
        "Sent: ", "Sent: ",
        "Contact info (optional)", "Contact info (optional)",
        "your.email@example.com", "your.email@example.com",
        "Join our community", "Join our community",
        "🔗 Discord Server  →", "🔗 Discord Server  →",
        "FAQ", "FAQ",
        "Donate", "Donate",
        "Changelog", "Changelog",
        "GitHub", "GitHub",
        "Reset defaults", "Reset defaults",
        "Apply & Save", "Apply & Save",
        "Cancel", "Cancel",
                "FlowWheel Settings", "FlowWheel Settings",
        "Share your feedback", "Share your feedback",
        "Your input helps us improve FlowWheel", "Your input helps us improve FlowWheel",
        "📎 Attach", "📎 Attach",
        "🗑️ Clear", "🗑️ Clear",
        "What type of feedback is this?", "What type of feedback is this?",
        "🐛 Bug", "🐛 Bug",
        "💡 Idea", "💡 Idea",
        "❓ Question", "❓ Question",
        "💬 Other", "💬 Other",
        "How would you rate your experience?", "How would you rate your experience?",
        "😞 Needs improvement", "😞 Needs improvement",
        "😕 Could be better", "😕 Could be better",
        "😐 Okay", "😐 Okay",
        "😊 Good", "😊 Good",
        "😍 Excellent!", "😍 Excellent!",
        "Submit feedback", "Submit feedback",
        "Sent: ", "Sent: ",
        "Contact info (optional)", "Contact info (optional)",
        "your.email@example.com", "your.email@example.com",
        "Join our community", "Join our community",
        "🔗 Discord Server  →", "🔗 Discord Server  →",
        "FAQ", "FAQ",
        "Donate", "Donate",
        "Changelog", "Changelog",
        "GitHub", "GitHub",
        "Reset defaults", "Reset defaults",
        "Apply & Save", "Apply & Save",
        "Cancel", "Cancel",
        
        ; UI - Stats
        "Thống kê FlowWheel", "FlowWheel Statistics",
        "📊 Thống kê sử dụng", "📊 Usage Statistics",
        "Tổng số cử chỉ đã thực hiện", "Total gestures performed",
        "Hạng: ", "Rank: ",
        "⏱️ Thời gian tiết kiệm được so với thao tác thủ công cũ: ", "⏱️ Time saved vs manual operations: ",
        "🏆 Cử chỉ dùng nhiều nhất", "🏆 Most used gesture",
        " lần", " times",
        "Phân tích chi tiết", "Detailed Analysis",
        "Chưa có dữ liệu cử chỉ nào.", "No gesture data yet.",
        "🏆 Khoe thành tích & Hạng lên Discord", "🏆 Share Achievement & Rank on Discord",
        "🗑️ Xóa thống kê", "🗑️ Clear statistics",
        "✓ Đóng", "✓ Close",
        "Bạn có chắc muốn xóa toàn bộ thống kê?", "Are you sure you want to clear all statistics?",
        "Xác nhận", "Confirm",
        "✓ Đã xóa thống kê", "✓ Statistics cleared",
        
        ; UI - About
        "Giới thiệu về FlowWheel", "About FlowWheel",
        "Chuyển động nhỏ - Dòng chảy lớn", "Small Motions - Big Flow",
        "Được sáng tạo và phát triển bởi", "Created and developed by",
        "Truy cập nhanh", "Quick Access",
        "⌨️ Truy cập nhanh", "⌨️ Quick Access",
        "Cài đặt", "Settings",
        "Hướng dẫn", "Reference Guide",
        "Thoát", "Exit",
        "Tạm dừng", "Pause",
        "Tải lại", "Reload",
        "☕ Ủng hộ phát triển", "☕ Support Development",
        "(Lỗi tải hình ảnh QR)", "(QR image load error)",
        "(Không tìm thấy QR.png)", "(QR.png not found)",
        "Mời tác giả một ly cà phê ☕", "Buy the author a coffee ☕",
        "© 2026 Minh Edward", "© 2026 Minh Edward",
        "Đóng", "Close",
        
        ; UI - Tray Menu
        "FlowWheel ", "FlowWheel ",
        "⚙️ Cài đặt`tCtrl+Alt+S", "⚙️ Settings`tCtrl+Alt+S",
        "📋 Tham khảo nhanh`tCtrl+Alt+H", "📋 Quick Reference`tCtrl+Alt+H",
        "📊 Thống kê", "📊 Statistics",
        "⏱️ Thời gian tiết kiệm : ", "⏱️ Time saved: ",
        "🎨 Phản hồi trực quan: ", "🎨 Visual Feedback: ",
        "Bật", "On",
        "Tắt", "Off",
        "⏸️ Tạm dừng FlowWheel`tCtrl+Alt+P", "⏸️ Pause FlowWheel`tCtrl+Alt+P",
        "🔄 Tải lại script`tCtrl+Alt+R", "🔄 Reload Script`tCtrl+Alt+R",
        "❌ Thoát`tCtrl+Alt+Q", "❌ Exit`tCtrl+Alt+Q",
        "✓ Đã bật phản hồi trực quan", "✓ Visual feedback enabled",
        "✗ Đã tắt phản hồi trực quan", "✗ Visual feedback disabled",
        
        ; UI - Welcome
        "Chào mừng đến với FlowWheel", "Welcome to FlowWheel",
        "Thao tác chuột mạnh mẽ cho Windows 10/11", "Powerful Mouse Gestures for Windows 10/11",
        "FlowWheel giúp chuột của bạn mạnh mẽ hơn với các cử chỉ thông minh, tăng tốc làm việc và điều khiển Windows dễ dàng.", "FlowWheel enhances your mouse with smart gestures, accelerating work and making Windows control effortless.",
        "⚠️ Yêu cầu phần cứng", "⚠️ Hardware Requirements",
        "Cần chuột có 2 nút bên hông (XButton1/XButton2).", "Requires a mouse with 2 side buttons (XButton1/XButton2).",
        "🚀 Bắt đầu nhanh", "🚀 Quick Start",
        "Hãy thử: Giữ CHUỘT PHẢI + cuộn để ", "Try: Hold RIGHT MOUSE + scroll to ",
        "chuyển tab trình duyệt", "switch browser tabs",
        "ngay!", " instantly!",
        "Nhấn Ctrl+Alt+H bất cứ lúc nào để xem hướng dẫn cử chỉ", "Press Ctrl+Alt+H anytime to view gesture guide",
        "Không hiển thị màn hình chào mừng này nữa", "Don't show this welcome screen again",
        "📖 Học cách dùng FlowWheel", "📖 Learn FlowWheel",
        "✓ Bắt đầu sử dụng", "✓ Start Using",
        
        ; Misc
        "Hiển thị", "Display",
        "✓ Cài đặt đã được áp dụng!", "✓ Settings applied!",
        "Ngôn ngữ / Language:", "Language / Ngôn ngữ:",
            "⚡ Hiệu năng / Độ nhạy", "⚡ Performance / Sensitivity",
            "🐛 Bật chế độ gỡ lỗi cho nhà phát triển", "🐛 Enable debug mode for developers",
            "🗂️ Bảo trì", "🗂️ Maintenance",
            "💬 Hỗ trợ", "💬 Support",
            "❓ Hỗ trợ & Tài nguyên", "❓ Support & Resources",
            "Đóng góp mã nguồn", "Contribute source code",
        "Ngôn ngữ đã thay đổi!", "Language changed!",
        "🌐 Ngôn ngữ / Language:", "🌐 Language / Ngôn ngữ:",
        
        ; Config Errors
        "Error loading config", "Error loading config",
        "Error saving config", "Error saving config",
        "Config Error", "Config Error",
        
        ; Rank Names
        "🐣 Người mới", "🐣 Newbie",
        "👑 Thần chuột", "👑 Mouse God",
        "🥉 Đồng khởi đầu", "🥉 Bronze Starter",
        
        ; Gesture Names for Stats
        "Độ sáng", "Brightness",
        "Phản hồi đã gửi", "Feedback sent",
        "Tắt/Bật tiếng", "Mute toggle",
        "Chụp màn hình", "Screenshot",
        "Đóng tab", "Close tab",
        "Khôi phục tab", "Restore tab",
        "Chuyển tab", "Switch tab",
        "Chọn taskbar", "Taskbar select",
        "Âm lượng", "Volume",
        "Ghim cửa sổ", "Snap window",
        "Chuyển cửa sổ", "Switch window",
        "Phóng to/Thu nhỏ", "Zoom",
        "Cuộn ngang", "Horizontal scroll",
        "Đóng (combo)", "Close (combo)",
        "Đóng từ taskbar", "Close from taskbar",
        "Ẩn nhanh (Ninja)", "Quick hide (Ninja)",
        "Ghim cửa sổ (pin)", "Pin window",
        
        ; Share Stats Messages
        "⚠️ Chưa có dữ liệu để chia sẻ!", "⚠️ No data to share yet!",
        "Bạn có muốn chia sẻ thành tích", "Do you want to share your achievement",
        "lên Discord không?", "on Discord?",
        "✅ Đã chia sẻ thành công!", "✅ Achievement shared successfully!",
        "⚠️ Không thể gửi: Mã lỗi", "⚠️ Cannot send: Error code",
        "⚠️ Không thể kết nối tới Discord!", "⚠️ Cannot connect to Discord!",
        
        ; Feedback Categories
        "🐛 Báo lỗi", "🐛 Bug Report",
        "💡 Ý tưởng", "💡 Suggestion",
        "❓ Hỏi đáp", "❓ Question",
        "💬 Khác", "💬 Other",
        
        ; Supporting Stats & Settings placeholders
        " lần", " times",
        " gestures", " gestures",
        "Ví dụ: MinhEdward#1234 hoặc Email...", "Example: MinhEdward#1234 or Email...",
        "Mô tả lỗi hoặc ý tưởng mới của bạn...", "Describe your bug or new idea...",
        "📷 Ảnh (PNG, JPG, BMP...)", "📷 Photo (PNG, JPG, BMP...)",
        "🎬 Video (MP4, AVI, MOV...)", "🎬 Video (MP4, AVI, MOV...)",
        "📄 Tài liệu (PDF, DOCX, TXT...)", "📄 Document (PDF, DOCX, TXT...)",
        "📦 File khác (ZIP, RAR...)", "📦 Other Files (ZIP, RAR...)",
        "📎 Đính kèm", "📎Attach",
        "⚠️ File quá lớn! Discord giới hạn 8MB", "⚠️ File too large! Discord limit is 8MB",
        "✅ Đã chọn file: ", "✅ File selected: ",
        "(Chưa chọn file)", "(No file selected)",
        "🗑️ Đã xóa file đính kèm", "🗑️ Attachment removed",
        
        ; System Info
        "═══ FLOWWHEEL SYSTEM INFO ═══\n", "═══ FLOWWHEEL SYSTEM INFO ═══\n",
        "Phiên bản: ", "Version: ",
        "Máy tính: ", "Computer: ",
        "OS: ", "OS: ",
        "User: ", "User: ",
        "Screen: ", "Screen: ",
        "\nCẤU HÌNH HIỆN TẠI:\n", "\nCURRENT CONFIGURATION:\n",
        "• Bước âm lượng: ", "• Volume step: ",
        "• Bước độ sáng: ", "• Brightness step: ",
        "• Timeout nút giữa: ", "• Middle button timeout: ",
        "\nTHỐNG KÊ SỬ DỤNG:\n", "\nUSAGE STATISTICS:\n",
        "Tổng thời gian tiết kiệm", "Total time saved",
        "📋 Đã sao chép thông tin hệ thống!", "📋 System info copied!",
        
        ; Webhook & Discord
        "⏳ Đang kiểm tra kết nối...", "⏳ Testing connection...",
        "✅ Kết nối thành công!", "✅ Connection successful!",
        "⚠️ Mã lỗi: ", "⚠️ Error code: ",
        "❌ Không thể kết nối: ", "❌ Connection failed: ",
        "⏳ FlowWheel vừa nhận phản hồi của bạn. Hãy đợi ", "⏳ FlowWheel received your feedback. Please wait ",
        " giây để gửi thêm", " seconds to send more",
        "⚠️ Vui lòng nhập nội dung hoặc đính kèm file!", "⚠️ Please enter content or attach a file!",
        "Người dùng ẩn danh", "Anonymous User",
        "📩 Feedback mới", "📩 New Feedback",
        "📁 Danh mục", "📁 Category",
        "👤 Người gửi", "👤 Sender",
        "⭐ Đánh giá", "⭐ Rating",
        "💻 Máy tính", "💻 Computer",
        "⚙️ Cấu hình", "⚙️ Config",
        "📝 Nội dung", "📝 Content",
        "⏳ Đang gửi dữ liệu...", "⏳ Sending data...",
        "✅ Phản hồi của bạn đã được tiếp nhận. Chúng tôi trân trọng sự đóng góp này!", "✅ Your feedback has been received. We appreciate your contribution!",
        "💬 Cảm ơn bạn đã gửi phản hồi. Chúng tôi trân trọng sự đóng góp này !", "💬 Thanks for your feedback. We appreciate your contribution !",
        
        ; System Info & Config
        "═══ FLOWWHEEL SYSTEM INFO ═══\n", "═══ FLOWWHEEL SYSTEM INFO ═══\n",
        "Phiên bản: ", "Version: ",
        "Máy tính: ", "Computer: ",
        "OS: ", "OS: ",
        "User: ", "User: ",
        "Screen: ", "Screen: ",
        "\nCẤU HÌNH HIỆN TẠI:\n", "\nCURRENT CONFIGURATION:\n",
        "• Bước âm lượng: ", "• Volume step: ",
        "• Bước độ sáng: ", "• Brightness step: ",
        "• Timeout nút giữa: ", "• Middle button timeout: ",
        "\nTHỐNG KÊ SỬ DỤNG:\n", "\nUSAGE STATISTICS:\n",
        "Tổng thời gian tiết kiệm", "Total time saved",
        "📋 Đã sao chép thông tin hệ thống!", "📋 System info copied!",
        
        ; Webhook Test
        "Kiểm tra kết nối từ FlowWheel", "Testing connection from FlowWheel",
        "⏳ Đang kiểm tra kết nối...", "⏳ Testing connection...",
        "✅ Kết nối thành công!", "✅ Connection successful!",
        "⚠️ Mã lỗi: ", "⚠️ Error code: ",
        "❌ Không thể kết nối: ", "❌ Connection failed: ",
        
        ; Config Import/Export
        "Export FlowWheel Config", "Export FlowWheel Config",
        "✓ Config exported successfully!", "✓ Config exported successfully!",
        "Export failed: ", "Export failed: ",
        "Export Error", "Export Error",
        "Import FlowWheel Config", "Import FlowWheel Config",
        "This will overwrite your current settings. Continue?", "This will overwrite your current settings. Continue?",
        "Import Config", "Import Config",
        "✓ Config imported! Reloading...", "✓ Config imported! Reloading...",
        "Import failed: ", "Import failed: ",
        "Import Error", "Import Error"
    )
)


; --- TRANSLATION FUNCTION ---
_t(str) {
    global cfg, LANG_MAP
    lang := (IsSet(cfg) && cfg.HasOwnProp("language")) ? cfg.language : "vi"
    if LANG_MAP.Has(lang) && LANG_MAP[lang].Has(str)
        return LANG_MAP[lang][str]
    else if LANG_MAP.Has("vi") && LANG_MAP["vi"].Has(str)
        return LANG_MAP["vi"][str]
    else
        return str
}

; --- TIME FORMATTING FUNCTION ---
FormatTimeSaved(totalSeconds) {
    hours := Floor(totalSeconds / 3600)
    minutes := Floor(Mod(totalSeconds, 3600) / 60)
    seconds := Mod(totalSeconds, 60)
    if (hours > 0)
        return hours . "h " . minutes . "m " . seconds . "s"
    else if (minutes > 0)
        return minutes . "m " . seconds . "s"
    else
        return seconds . "s"
}