; ============================================================================
; FLOWWHEEL - LANGUAGE MAP (Vietnamese / English)
; ============================================================================

; --- PLAY GESTURE SOUND FEEDBACK ---
PlayGestureSound() {
    global cfg
    if !cfg.feedback.HasOwnProp("soundEnabled") || !cfg.feedback.soundEnabled
        return
    ; Phát âm thanh nhẹ nhàng từ file nếu có
    ; Kiểm tra trong thư mục script hoặc thư mục làm việc
    soundFile := A_ScriptDir . "\..\resources\sounds\FlowWheelSoundFeedback.wav"
    if !FileExist(soundFile)
        soundFile := A_ScriptDir . "\..\resources\FlowWheelSoundFeedback.wav" ; Legacy path
    if FileExist(soundFile)
        SoundPlay soundFile, "wait"
    else
        SoundBeep 1000, 80 ; fallback nếu không tìm thấy file
}

; --- LANGUAGE MANAGEMENT FUNCTIONS ---
_t(str) {
    global cfg
    
    ; Nếu đang dùng tiếng Anh và có bản dịch, trả về bản tiếng Anh
    if (cfg.language = "en" && langMap_en.Has(str)) {
        return langMap_en[str]
    }
    
    ; Ngược lại trả về chuỗi gốc (tiếng Việt)
    return str
}

; --- VIETNAMESE STRINGS (DEFAULT) ---
langMap := Map(
    ; ===== CHUNG =====
    "Giới thiệu về FlowWheel", "Giới thiệu về FlowWheel",
    "FlowWheel", "FlowWheel",
    "Chuyển động nhỏ - Dòng chảy lớn", "Chuyển động nhỏ - Dòng chảy lớn",
    "Được sáng tạo và phát triển bởi", "Được sáng tạo và phát triển bởi",
    "Minh Edward 🚀", "Minh Edward 🚀",
    "⌨️ Truy cập nhanh", "⌨️ Truy cập nhanh",
    "Ctrl + Alt + S  →  Cài đặt", "Ctrl + Alt + S  →  Cài đặt",
    "Ctrl + Alt + H  →  Tham khảo nhanh", "Ctrl + Alt + H  →  Tham khảo nhanh",
    "Ctrl + Alt + Q  →  Thoát ứng dụng", "Ctrl + Alt + Q  →  Thoát ứng dụng",
    "Ctrl + Alt + P  →  Tạm dừng", "Ctrl + Alt + P  →  Tạm dừng",
    "☕ Ủng hộ phát triển", "☕ Ủng hộ phát triển",
    "(Lỗi tải hình ảnh QR)", "(Lỗi tải hình ảnh QR)",
    "(Không tìm thấy QR.png)", "(Không tìm thấy QR.png)",
    "Path: ", "Path: ",
    "Mời tác giả một ly cà phê ☕", "Mời tác giả một ly cà phê ☕",
    "© 2026 Minh Edward", "© 2026 Minh Edward",
    "Đóng", "Đóng",
    
    ; ===== HƯỚNG DẪN CỬ CHỈ =====
    "FlowWheel - Bảng Tham Khảo Nhanh", "FlowWheel - Bảng Tham Khảo Nhanh",
    "Bảng Tham Khảo Nhanh", "Bảng Tham Khảo Nhanh",
    "Nhấn để mở cài đặt", "Nhấn để mở cài đặt",
    "🖱️ Cấu Hình Thiết Bị", "🖱️ Cấu Hình Thiết Bị",
    "Tối ưu cho chuột 5 nút", "Tối ưu cho chuột 5 nút",
    "🌐Điều hướng Web / Trình duyệt", "🌐Điều hướng Web / Trình duyệt",
    "RButton + Wheel", "RButton + Wheel",
    "Chuyển Tab trình `n duyệt", "Chuyển Tab trình `n duyệt",
    "RButton + MButton", "RButton + MButton",
    "Đóng Tab nhanh", "Đóng Tab nhanh",
    "LButton + MButton", "LButton + MButton",
    "Khôi phục Tab đã `n đóng", "Khôi phục Tab đã `n đóng",
    "RButton + Wheel L/R hoặc Shift + Wheel ", "RButton + Wheel L/R hoặc Shift + Wheel ",
    "Cuộn ngang ", "Cuộn ngang ",
    "🖥️Quản lý Cửa sổ / Hệ thống", "🖥️Quản lý Cửa sổ / Hệ thống",
    "X1 + Wheel /+ RButton", "X1 + Wheel /+ RButton",
    "Chuyển / đóng cửa `n sổ (Alt+Tab)", "Chuyển / đóng cửa `n sổ (Alt+Tab)",
    "X2 + Wheel", "X2 + Wheel",
    "Chọn ứng dụng Taskbar", "Chọn ứng dụng Taskbar",
    "X1 + MButton", "X1 + MButton",
    "Đóng cửa sổ nhanh", "Đóng cửa sổ nhanh",
    "X2 + MButton", "X2 + MButton",
    "Show/Hide Desktop", "Show/Hide Desktop",
    "🎵Điều khiển Đa phương tiện", "🎵Điều khiển Đa phương tiện",
    "RButton + X1 + Wheel", "RButton + X1 + Wheel",
    "Điều chỉnh âm lượng", "Điều chỉnh âm lượng",
    "RButton + X2 + Wheel", "RButton + X2 + Wheel",
    "Điều chỉnh độ sáng", "Điều chỉnh độ sáng",
    "MButton (Nhấn giữ)", "MButton (Nhấn giữ)",
    "Bật/Tắt âm thanh (Mute)", "Bật/Tắt âm thanh (Mute)",
    "MButton + Wheel", "MButton + Wheel",
    "Phóng to / Thu nhỏ (Zoom)", "Phóng to / Thu nhỏ (Zoom)",
    "🛠️Tiện ích / Nâng cao", "🛠️Tiện ích / Nâng cao",
    "X1 + X2", "X1 + X2",
    "Chụp màn hình nhanh", "Chụp màn hình nhanh",
    "RButton + X1/X2", "RButton + X1/X2",
    "Ghim cửa sổ (Snap)", "Ghim cửa sổ (Snap)",
    "X1 (on Taskbar)", "X1 (on Taskbar)",
    "Đóng ứng dụng từ Taskbar", "Đóng ứng dụng từ Taskbar",
    "⚡ Truy cập nhanh", "⚡ Truy cập nhanh",
    "Cài đặt", "Cài đặt",
    "Hướng dẫn", "Hướng dẫn",
    "Thoát", "Thoát",
    "Tạm dừng", "Tạm dừng",
    "Tải lại", "Tải lại",
    "💡 Hãy vào Cài đặt để tùy chỉnh cử chỉ theo ý bạn!", "💡 Hãy vào Cài đặt để tùy chỉnh cử chỉ theo ý bạn!",
    "Nhấn Ctrl+Alt+H bất cứ lúc nào để mở lại hướng dẫn này", "Nhấn Ctrl+Alt+H bất cứ lúc nào để mở lại hướng dẫn này",
    "✓ ĐÃ HIỂU!", "✓ ĐÃ HIỂU!",
    
    ; ===== CÀI ĐẶT =====
    "FlowWheel Settings", "FlowWheel Settings",
    "Cài đặt", "Cài đặt",
    "Quản lý và tùy chỉnh trải nghiệm FlowWheel của bạn", "Quản lý và tùy chỉnh trải nghiệm FlowWheel của bạn",
    "🎯 Cử chỉ", "🎯 Cử chỉ",
    "🎨 Hiển thị", "🎨 Hiển thị",
    "⚙️ Nâng cao", "⚙️ Nâng cao",
    "💬 Hỗ trợ", "💬 Hỗ trợ",
    "🌐 Trình duyệt_Cuộn", "🌐 Trình duyệt_Cuộn",
    "Chuyển Tab", "Chuyển Tab",
    "Đóng Tab nhanh", "Đóng Tab nhanh",
    "Khôi phục Tab", "Khôi phục Tab",
    "Cuộn ngang", "Cuộn ngang",
    "🎵 Giải trí_Media", "🎵 Giải trí_Media",
    "Âm lượng", "Âm lượng",
    "Độ sáng", "Độ sáng",
    "Tắt/Bật âm", "Tắt/Bật âm",
    "Phóng to/Thu nhỏ", "Phóng to/Thu nhỏ",
    "🖥️ Hệ thống_Cửa sổ", "🖥️ Hệ thống_Cửa sổ",
    "Chuyển/Đóng cửa sổ", "Chuyển/Đóng cửa sổ",
    "App Taskbar", "App Taskbar",
    "Đóng cửa sổ", "Đóng cửa sổ",
    "🛠️ Công cụ_Tiện ích", "🛠️ Công cụ_Tiện ích",
    "Ẩn/Hiện Desktop", "Ẩn/Hiện Desktop",
    "Chụp màn hình", "Chụp màn hình",
    "Ghim cửa sổ", "Ghim cửa sổ",
    "Đóng app trên Taskbar", "Đóng app trên Taskbar",
    "Cài đặt nâng cao", "Cài đặt nâng cao",
    "Cài đặt nhanh", "Cài đặt nhanh",
    "Phản hồi trực quan", "Phản hồi trực quan",
    " Hiển thị phản hồi khi thao tác", " Hiển thị phản hồi khi thao tác",
    "Âm thanh phản hồi", "Âm thanh phản hồi",
    "🔊 Nghe thử", "🔊 Nghe thử",
    "Thời gian hiển thị:", "Thời gian hiển thị:",
    "ms", "ms",
    "Vị trí:", "Vị trí:",
    "Gần con trỏ", "Gần con trỏ",
    "Giữa màn hình", "Giữa màn hình",
    "Góc trên phải", "Góc trên phải",
    "👁️ Xem thử", "👁️ Xem thử",
    "🔧 Hệ thống", "🔧 Hệ thống",
    "Ngôn ngữ/Language:", "Ngôn ngữ/Language:",
    "Tiếng Việt", "Tiếng Việt",
    "English", "English",
    "Khởi động cùng Windows", "Khởi động cùng Windows",
    "Hiện màn hình chào mừng", "Hiện màn hình chào mừng",
    "⚡ Hiệu năng", "⚡ Hiệu năng",
    "Bước âm lượng:", "Bước âm lượng:",
    "Bước độ sáng:", "Bước độ sáng:",
    "Thời gian nhấn giữ MButton:", "Thời gian nhấn giữ MButton:",
    "Gia tốc cuộn:", "Gia tốc cuộn:",
    "🐛 Chế độ gỡ lỗi", "🐛 Chế độ gỡ lỗi",
    "🗂️ Bảo trì", "🗂️ Bảo trì",
    "📁 Mở thư mục", "📁 Mở thư mục",
    "📤 Xuất", "📤 Xuất",
    "📥 Nhập", "📥 Nhập",
    "Share your feedback", "Share your feedback",
    "Your input helps us improve FlowWheel", "Your input helps us improve FlowWheel",
    "Tell us what you think...", "Tell us what you think...",
    "📎 Attach", "📎 Attach",
    "🗑️ Clear", "🗑️ Clear",
    "What type of feedback is this?", "What type of feedback is this?",
    "🐛 Bug", "🐛 Bug",
    "💡 Idea", "💡 Idea",
    "❓ Question", "❓ Question",
    "💬 Other", "💬 Other",
    "How would you rate your experience?", "How would you rate your experience?",
    "😞 Needs improvement", "😞 Needs improvement",
    "😕 Could be better", "😕 Could be better",
    "😐 Okay", "😐 Okay",
    "😊 Good", "😊 Good",
    "😍 Excellent!", "😍 Excellent!",
    "Contact info (optional)", "Contact info (optional)",
    "your.email@example.com", "your.email@example.com",
    "Join our community", "Join our community",
    "🔗 Discord Server  →", "🔗 Discord Server  →",
    "Submit feedback", "Submit feedback",
    "FAQ", "FAQ",
    "Donate", "Donate",
    "Changelog", "Changelog",
    "GitHub", "GitHub",
    "Sent: ", "Sent: ",
    "↺ Reset defaults", "↺ Reset defaults",
    "✗ Close", "✗ Close",
    "Reset all settings to defaults?", "Reset all settings to defaults?",
    "Reset Configuration", "Reset Configuration",
    "Yes", "Yes",
    "No", "No",
    "Reload UI to apply language?", "Reload UI to apply language?",
    "Confirm", "Confirm",
    "✓ Settings applied!", "✓ Settings applied!",
    "Language changed!", "Language changed!",
    "✓ Reset to defaults", "✓ Reset to defaults",
    
    ; ===== THỐNG KÊ =====
    "Thống kê FlowWheel", "Thống kê FlowWheel",
    "📊 Thống kê sử dụng", "📊 Thống kê sử dụng",
    "Tổng số cử chỉ đã thực hiện", "Tổng số cử chỉ đã thực hiện",
    "Hạng: ", "Hạng: ",
    "🐣 Người mới", "🐣 Người mới",
    "⏱️ Thời gian tiết kiệm được so với thao tác thủ công cũ: ", "⏱️ Thời gian tiết kiệm được so với thao tác thủ công cũ: ",
    "🏆 Cử chỉ dùng nhiều nhất", "🏆 Cử chỉ dùng nhiều nhất",
    " lần", " lần",
    "Phân tích chi tiết", "Phân tích chi tiết",
    "🏆 Khoe thành tích & Hạng lên Discord", "🏆 Khoe thành tích & Hạng lên Discord",
    "🗑️ Xóa thống kê", "🗑️ Xóa thống kê",
    "✓ Đóng", "✓ Đóng",
    "Bạn có chắc muốn xóa toàn bộ thống kê?", "Bạn có chắc muốn xóa toàn bộ thống kê?",
    "Xác nhận", "Xác nhận",
    "✓ Đã xóa thống kê", "✓ Đã xóa thống kê",
    "Chưa có dữ liệu cử chỉ nào.", "Chưa có dữ liệu cử chỉ nào.",
    
    ; ===== CỬ CHỈ THỰC TẾ =====
    "🔊 Âm lượng", "🔊 Âm lượng",
    "☀️ Độ sáng", "☀️ Độ sáng",
    "↔️ Cuộn sang phải", "↔️ Cuộn sang phải",
    "↔️ Cuộn sang trái", "↔️ Cuộn sang trái",
    "📌 Đã bỏ ghim cửa sổ", "📌 Đã bỏ ghim cửa sổ",
    "📍 Đã ghim cửa sổ (Always on Top)", "📍 Đã ghim cửa sổ (Always on Top)",
    "⚠️ Không thể ghim cửa sổ", "⚠️ Không thể ghim cửa sổ",
    "❌ Đã đóng ứng dụng (Alt+Tab)", "❌ Đã đóng ứng dụng (Alt+Tab)",
    "❌ Đã đóng tab trình duyệt", "❌ Đã đóng tab trình duyệt",
    "♻️ Đã khôi phục tab vừa đóng", "♻️ Đã khôi phục tab vừa đóng",
    "❌ Đã đóng cửa sổ", "❌ Đã đóng cửa sổ",
    "💻 Show/Hide Desktop: Ẩn/Hiện Desktop", "💻 Show/Hide Desktop: Ẩn/Hiện Desktop",
    "🔇 Đã bật/tắt tiếng hệ thống", "🔇 Đã bật/tắt tiếng hệ thống",
    "📸 Đã chụp màn hình!", "📸 Đã chụp màn hình!",
    "⬅️ Đã ghim cửa sổ sang trái", "⬅️ Đã ghim cửa sổ sang trái",
    "➡️ Đã ghim cửa sổ sang phải", "➡️ Đã ghim cửa sổ sang phải",
    "❌ Đóng window từ Taskbar (hover thumbnail)", "❌ Đóng window từ Taskbar (hover thumbnail)",
    "❌ Đóng window từ Taskbar", "❌ Đóng window từ Taskbar",
    "🔍 Phóng to", "🔍 Phóng to",
    "🔍 Thu nhỏ", "🔍 Thu nhỏ",
    "🔄 Chuyển cửa sổ tiếp theo", "🔄 Chuyển cửa sổ tiếp theo",
    "🔄 Chuyển cửa sổ trước", "🔄 Chuyển cửa sổ trước",
    "🔄 Chuyển tab tiếp theo", "🔄 Chuyển tab tiếp theo",
    "🔄 Chuyển tab trước", "🔄 Chuyển tab trước",
    "🔳 Đang chọn taskbar (phải)", "🔳 Đang chọn taskbar (phải)",
    "🔳 Đang chọn taskbar (trái)", "🔳 Đang chọn taskbar (trái)",
    "Preview", "Preview",
    
    ; ===== MÀN HÌNH CHÀO MỪNG =====
    "👋 Chào mừng đến với FlowWheel", "👋 Chào mừng đến với FlowWheel",
    "Thao tác chuột mạnh mẽ cho Windows 10/11", "Thao tác chuột mạnh mẽ cho Windows 10/11",
    "FlowWheel giúp chuột của bạn mạnh mẽ hơn với các cử chỉ thông minh, tăng tốc làm việc và điều khiển Windows dễ dàng.", "FlowWheel giúp chuột của bạn mạnh mẽ hơn với các cử chỉ thông minh, tăng tốc làm việc và điều khiển Windows dễ dàng.",
    "⚠️ Yêu cầu phần cứng", "⚠️ Yêu cầu phần cứng",
    "Cần chuột có 2 nút bên hông (XButton1/XButton2).", "Cần chuột có 2 nút bên hông (XButton1/XButton2).",
    "🚀 Bắt đầu nhanh", "🚀 Bắt đầu nhanh",
    "Hãy thử: Giữ CHUỘT PHẢI + cuộn để ", "Hãy thử: Giữ CHUỘT PHẢI + cuộn để ",
    "chuyển tab trình duyệt", "chuyển tab trình duyệt",
    "ngay!", "ngay!",
    "Nhấn Ctrl+Alt+H bất cứ lúc nào để xem hướng dẫn cử chỉ", "Nhấn Ctrl+Alt+H bất cứ lúc nào để xem hướng dẫn cử chỉ",
    "🌐 Ngôn ngữ / Language:", "🌐 Ngôn ngữ / Language:",
    "Không hiển thị màn hình chào mừng này nữa", "Không hiển thị màn hình chào mừng này nữa",
    "📖 Học cách dùng", "📖 Học cách dùng",
    "✓ Bắt đầu sử dụng", "✓ Bắt đầu sử dụng",
    
    ; ===== TRAY MENU =====
    "FlowWheel ", "FlowWheel ",
    "⚙️ Cài đặt`tCtrl+Alt+S", "⚙️ Cài đặt`tCtrl+Alt+S",
    "📋 Tham khảo nhanh`tCtrl+Alt+H", "📋 Tham khảo nhanh`tCtrl+Alt+H",
    "📊 Thống kê", "📊 Thống kê",
    "⏱️ Thời gian tiết kiệm : ", "⏱️ Thời gian tiết kiệm : ",
    "🎨 Phản hồi trực quan: ", "🎨 Phản hồi trực quan: ",
    "Bật", "Bật",
    "Tắt", "Tắt",
    "⏸️ Tạm dừng FlowWheel`tCtrl+Alt+P", "⏸️ Tạm dừng FlowWheel`tCtrl+Alt+P",
    "🔄 Tải lại script`tCtrl+Alt+R", "🔄 Tải lại script`tCtrl+Alt+R",
    "❌ Thoát`tCtrl+Alt+Q", "❌ Thoát`tCtrl+Alt+Q",
    "✓ Đã bật phản hồi trực quan", "✓ Đã bật phản hồi trực quan",
    "✗ Đã tắt phản hồi trực quan", "✗ Đã tắt phản hồi trực quan",
    "FlowWheel đang chạy ở khay hệ thống 🔔", "FlowWheel đang chạy ở khay hệ thống 🔔",
    "Nhấn vào mũi tên ^ ở khay hệ thống để xem biểu tượng", "Nhấn vào mũi tên ^ ở khay hệ thống để xem biểu tượng",
    
    ; ===== HỆ THỐNG HỖ TRỢ =====
    "Vui lòng nhập nội dung hoặc đính kèm file!", "Vui lòng nhập nội dung hoặc đính kèm file!",
    "File quá lớn! Discord giới hạn 8MB", "File quá lớn! Discord giới hạn 8MB",
    "(Chưa chọn file)", "(Chưa chọn file)",
    "✅ Đã chọn file: ", "✅ Đã chọn file: ",
    "🗑️ Đã xóa file đính kèm", "🗑️ Đã xóa file đính kèm",
    "⚠️ FlowWheel vừa nhận phản hồi của bạn. Hãy đợi ", "⚠️ FlowWheel vừa nhận phản hồi của bạn. Hãy đợi ",
    " giây để gửi thêm", " giây để gửi thêm",
    "Người dùng ẩn danh", "Người dùng ẩn danh",
    "⏳ Đang gửi dữ liệu...", "⏳ Đang gửi dữ liệu...",
    "✅ Phản hồi của bạn đã được tiếp nhận. Chúng tôi trân trọng sự đóng góp này!", "✅ Phản hồi của bạn đã được tiếp nhận. Chúng tôi trân trọng sự đóng góp này!",
    "💬 Cảm ơn bạn đã gửi phản hồi. Chúng tôi trân trọng sự đóng góp này !", "💬 Cảm ơn bạn đã gửi phản hồi. Chúng tôi trân trọng sự đóng góp này !",
    "⚠️ Không thể điều chỉnh độ sáng!", "⚠️ Không thể điều chỉnh độ sáng!",
    "⚠️ Chưa có dữ liệu để chia sẻ!", "⚠️ Chưa có dữ liệu để chia sẻ!",
    "Bạn có muốn chia sẻ thành tích", "Bạn có muốn chia sẻ thành tích",
    " lên Discord không?", " lên Discord không?",
    "✅ Đã chia sẻ thành tích thành công!", "✅ Đã chia sẻ thành tích thành công!",
    "⚠️ Không thể gửi: Mã lỗi", "⚠️ Không thể gửi: Mã lỗi",
    "⚠️ Không thể kết nối tới Discord!", "⚠️ Không thể kết nối tới Discord!",
    
    ; ===== XUẤT/NHẬP CẤU HÌNH =====
    "Export FlowWheel Config", "Export FlowWheel Config",
    "✓ Config exported successfully!", "✓ Config exported successfully!",
    "Export failed: ", "Export failed: ",
    "Export Error", "Export Error",
    "Import FlowWheel Config", "Import FlowWheel Config",
    "This will overwrite your current settings. Continue?", "This will overwrite your current settings. Continue?",
    "Import Config", "Import Config",
    "✓ Config imported! Reloading...", "✓ Config imported! Reloading...",
    "Import failed: ", "Import failed: ",
    "Import Error", "Import Error",
    
    ; ===== THÔNG BÁO LỖI =====
    "Error loading config", "Error loading config",
    "Config Error", "Config Error",
    "Error saving config", "Error saving config",
    
    ; ===== PAUSE/RESUME =====
    "⏸️ FlowWheel PAUSED`nPress Ctrl+Alt+P to resume", "⏸️ FlowWheel PAUSED`nPress Ctrl+Alt+P to resume",
    "▶️ FlowWheel RESUMED", "▶️ FlowWheel RESUMED"
)

; --- ENGLISH STRINGS (TRANSLATIONS) ---
langMap_en := Map(
    ; ===== COMMON =====
    "Giới thiệu về FlowWheel", "About FlowWheel",
    "FlowWheel", "FlowWheel",
    "Chuyển động nhỏ - Dòng chảy lớn", "Small Actions - Big Flow",
    "Được sáng tạo và phát triển bởi", "Created and developed by",
    "Minh Edward 🚀", "Minh Edward 🚀",
    "⌨️ Truy cập nhanh", "⌨️ Quick Access",
    "Ctrl + Alt + S  →  Cài đặt", "Ctrl + Alt + S  →  Settings",
    "Ctrl + Alt + H  →  Tham khảo nhanh", "Ctrl + Alt + H  →  Quick Reference",
    "Ctrl + Alt + Q  →  Thoát ứng dụng", "Ctrl + Alt + Q  →  Quit Application",
    "Ctrl + Alt + P  →  Tạm dừng", "Ctrl + Alt + P  →  Pause",
    "☕ Ủng hộ phát triển", "☕ Support Development",
    "(Lỗi tải hình ảnh QR)", "(Error loading QR image)",
    "(Không tìm thấy QR.png)", "(QR.png not found)",
    "Path: ", "Path: ",
    "Mời tác giả một ly cà phê ☕", "Buy the author a coffee ☕",
    "© 2026 Minh Edward", "© 2026 Minh Edward",
    "Đóng", "Close",
    
    ; ===== GESTURE GUIDE =====
    "FlowWheel - Bảng Tham Khảo Nhanh", "FlowWheel - Quick Reference Guide",
    "Bảng Tham Khảo Nhanh", "Quick Reference Guide",
    "Nhấn để mở cài đặt", "Open settings",
    "🖱️ Cấu Hình Thiết Bị", "🖱️ Device Configuration",
    "Tối ưu cho chuột 5 nút", "Optimized for 5-button mouse",
    "🌐Điều hướng Web / Trình duyệt", "🌐Web / Browser Navigation",
    "RButton + Wheel", "RButton + Wheel",
    "Chuyển Tab trình `n duyệt", "Switch browser `n tabs",
    "RButton + MButton", "RButton + MButton",
    "Đóng Tab nhanh", "Close tab quickly",
    "LButton + MButton", "LButton + MButton",
    "Khôi phục Tab đã `n đóng", "Restore closed `n tab",
    "RButton + Wheel L/R hoặc Shift + Wheel ", "RButton + Wheel L/R or Shift + Wheel ",
    "Cuộn ngang ", "Horizontal scroll ",
    "🖥️Quản lý Cửa sổ / Hệ thống", "🖥️Window / System Management",
    "X1 + Wheel /+ RButton", "X1 + Wheel /+ RButton",
    "Chuyển / đóng cửa `n sổ (Alt+Tab)", "Switch/close window `n (Alt+Tab)",
    "X2 + Wheel", "X2 + Wheel",
    "Chọn ứng dụng Taskbar", "Select Taskbar app",
    "X1 + MButton", "X1 + MButton",
    "Đóng cửa sổ nhanh", "Close window quickly",
    "X2 + MButton", "X2 + MButton",
    "Show/Hide Desktop", "Show/Hide Desktop",
    "🎵Điều khiển Đa phương tiện", "🎵Media Controls",
    "RButton + X1 + Wheel", "RButton + X1 + Wheel",
    "Điều chỉnh âm lượng", "Adjust volume",
    "RButton + X2 + Wheel", "RButton + X2 + Wheel",
    "Điều chỉnh độ sáng", "Adjust brightness",
    "MButton (Nhấn giữ)", "MButton (Hold)",
    "Bật/Tắt âm thanh (Mute)", "Toggle mute",
    "MButton + Wheel", "MButton + Wheel",
    "Phóng to / Thu nhỏ (Zoom)", "Zoom in/out",
    "🛠️Tiện ích / Nâng cao", "🛠️Tools / Advanced",
    "X1 + X2", "X1 + X2",
    "Chụp màn hình nhanh", "Quick screenshot",
    "RButton + X1/X2", "RButton + X1/X2",
    "Ghim cửa sổ (Snap)", "Snap window",
    "X1 (on Taskbar)", "X1 (on Taskbar)",
    "Đóng ứng dụng từ Taskbar", "Close app from Taskbar",
    "⚡ Truy cập nhanh", "⚡ Quick Access",
    "Cài đặt", "Settings",
    "Hướng dẫn", "Guide",
    "Thoát", "Quit",
    "Tạm dừng", "Pause",
    "Tải lại", "Reload",
    "💡 Hãy vào Cài đặt để tùy chỉnh cử chỉ theo ý bạn!", "💡 Go to Settings to customize gestures as you like!",
    "Nhấn Ctrl+Alt+H bất cứ lúc nào để mở lại hướng dẫn này", "Press Ctrl+Alt+H anytime to reopen this guide",
    "✓ ĐÃ HIỂU!", "✓ GOT IT!",
    
    ; ===== SETTINGS =====
    "FlowWheel Settings", "FlowWheel Settings",
    "Cài đặt", "Settings",
    "Quản lý và tùy chỉnh trải nghiệm FlowWheel của bạn", "Manage and customize your FlowWheel experience",
    "🎯 Cử chỉ", "🎯 Gestures",
    "🎨 Hiển thị", "🎨 Display",
    "⚙️ Nâng cao", "⚙️ Advanced",
    "💬 Hỗ trợ", "💬 Support",
    "🌐 Trình duyệt_Cuộn", "🌐 Browser_Scrolling",
    "Chuyển Tab", "Switch Tab",
    "Đóng Tab nhanh", "Close Tab",
    "Khôi phục Tab", "Restore Tab",
    "Cuộn ngang", "Horizontal Scroll",
    "🎵 Giải trí_Media", "🎵 Media_Entertainment",
    "Âm lượng", "Volume",
    "Độ sáng", "Brightness",
    "Tắt/Bật âm", "Mute",
    "Phóng to/Thu nhỏ", "Zoom",
    "🖥️ Hệ thống_Cửa sổ", "🖥️ System_Windows",
    "Chuyển/Đóng cửa sổ", "Switch/Close Window",
    "App Taskbar", "Taskbar App",
    "Đóng cửa sổ", "Close Window",
    "🛠️ Công cụ_Tiện ích", "🛠️ Tools_Utilities",
    "Ẩn/Hiện Desktop", "Show/Hide Desktop",
    "Chụp màn hình", "Screenshot",
    "Ghim cửa sổ", "Snap Window",
    "Đóng app trên Taskbar", "Close Taskbar App",
    "Cài đặt nâng cao", "Advanced settings",
    "Cài đặt nhanh", "Quick settings",
    "Phản hồi trực quan", "Visual Feedback",
    " Hiển thị phản hồi khi thao tác", " Show visual feedback on actions",
    "Âm thanh phản hồi", "Sound feedback",
    "🔊 Nghe thử", "🔊 Test sound",
    "Thời gian hiển thị:", "Display duration:",
    "ms", "ms",
    "Vị trí:", "Position:",
    "Gần con trỏ", "Near cursor",
    "Giữa màn hình", "Screen center",
    "Góc trên phải", "Top right",
    "👁️ Xem thử", "👁️ Preview",
    "🔧 Hệ thống", "🔧 System",
    "Ngôn ngữ/Language:", "Ngôn ngữ/Language:",
    "Tiếng Việt", "Vietnamese",
    "English", "English",
    "Khởi động cùng Windows", "Start with Windows",
    "Hiện màn hình chào mừng", "Show welcome screen",
    "⚡ Hiệu năng", "⚡ Performance",
    "Bước âm lượng:", "Volume step:",
    "Bước độ sáng:", "Brightness step:",
    "Thời gian nhấn giữ MButton:", "MButton hold time:",
    "Gia tốc cuộn:", "Scroll acceleration:",
    "🐛 Chế độ gỡ lỗi", "🐛 Debug mode",
    "🗂️ Bảo trì", "🗂️ Maintenance",
    "📁 Mở thư mục", "📁 Open folder",
    "📤 Xuất", "📤 Export",
    "📥 Nhập", "📥 Import",
        "Gửi phản hồi của bạn", "Share your feedback",
    "Ý kiến của bạn giúp FlowWheel tốt hơn!", "Your input helps us improve FlowWheel",
    "Hãy chia sẻ ý kiến, góp ý hoặc vấn đề bạn gặp phải...", "Tell us what you think...",
    "📎 Đính kèm", "📎 Attach",
    "🗑️ Xóa tệp", "🗑️ Clear",
    "Phản hồi của bạn thuộc loại nào?", "What type of feedback is this?",
    "🐛 Lỗi", "🐛 Bug",
    "💡 Ý tưởng", "💡 Idea",
    "❓ Câu hỏi", "❓ Question",
    "💬 Khác", "💬 Other",
    "Bạn đánh giá trải nghiệm FlowWheel thế nào?", "How would you rate your experience?",
    "😍 Xuất sắc!", "😍 Excellent!",
    "Thông tin liên hệ (không bắt buộc)", "Contact info (optional)",
    "email.cua.ban@email.com", "your.email@example.com",
    "Tham gia cộng đồng FlowWheel", "Join our community",
    "🔗 Tham gia Discord  →", "🔗 Discord Server  →",
    "Gửi phản hồi", "Submit feedback",
    "FAQ", "FAQ",
    "Donate", "Donate",
    "Changelog", "Changelog",
    "GitHub", "GitHub",
    "Sent: ", "Sent: ",
    "Đặt lại mặc định", "Reset defaults",
    "✗ Đóng", "✗ Close",
    "Cài đặt nâng cao", "Advanced settings",
    "Cài đặt nhanh", "Quick settings",
    "Reset all settings to defaults?", "Reset all settings to defaults?",
    "Reset Configuration", "Reset Configuration",
    "Yes", "Yes",
    "No", "No",
    "Reload UI to apply language?", "Reload UI to apply language?",
    "Confirm", "Confirm",
    "✓ Settings applied!", "✓ Settings applied!",
    "Language changed!", "Language changed!",
    "✓ Reset to defaults", "✓ Reset to defaults",
    
    ; ===== STATISTICS =====
    "Thống kê FlowWheel", "FlowWheel Statistics",
    "📊 Thống kê sử dụng", "📊 Usage Statistics",
    "Tổng số cử chỉ đã thực hiện", "Total gestures performed",
    "Hạng: ", "Rank: ",
    "🐣 Người mới", "🐣 Newbie",
    "⏱️ Thời gian tiết kiệm được so với thao tác thủ công cũ: ", "⏱️ Time saved vs manual operations: ",
    "🏆 Cử chỉ dùng nhiều nhất", "🏆 Most used gesture",
    " lần", " times",
    "Phân tích chi tiết", "Detailed analysis",
    "🏆 Khoe thành tích & Hạng lên Discord", "🏆 Share achievements & Rank to Discord",
    "🗑️ Xóa thống kê", "🗑️ Clear statistics",
    "✓ Đóng", "✓ Close",
    "Bạn có chắc muốn xóa toàn bộ thống kê?", "Are you sure you want to clear all statistics?",
    "Xác nhận", "Confirm",
    "✓ Đã xóa thống kê", "✓ Statistics cleared",
    "Chưa có dữ liệu cử chỉ nào.", "No gesture data yet.",
    
    ; ===== ACTUAL GESTURES =====
    "🔊 Âm lượng", "🔊 Volume",
    "☀️ Độ sáng", "☀️ Brightness",
    "↔️ Cuộn sang phải", "↔️ Scroll right",
    "↔️ Cuộn sang trái", "↔️ Scroll left",
    "📌 Đã bỏ ghim cửa sổ", "📌 Window unpinned",
    "📍 Đã ghim cửa sổ (Always on Top)", "📍 Window pinned (Always on Top)",
    "⚠️ Không thể ghim cửa sổ", "⚠️ Cannot pin window",
    "❌ Đã đóng ứng dụng (Alt+Tab)", "❌ App closed (Alt+Tab)",
    "❌ Đã đóng tab trình duyệt", "❌ Browser tab closed",
    "♻️ Đã khôi phục tab vừa đóng", "♻️ Tab restored",
    "❌ Đã đóng cửa sổ", "❌ Window closed",
    "💻 Show/Hide Desktop: Ẩn/Hiện Desktop", "💻 Show/Hide Desktop",
    "🔇 Đã bật/tắt tiếng hệ thống", "🔇 System toggled mute",
    "📸 Đã chụp màn hình!", "📸 Screenshot taken!",
    "⬅️ Đã ghim cửa sổ sang trái", "⬅️ Window snapped left",
    "➡️ Đã ghim cửa sổ sang phải", "➡️ Window snapped right",
    "❌ Đóng window từ Taskbar (hover thumbnail)", "❌ Close window from Taskbar (hover thumbnail)",
    "❌ Đóng window từ Taskbar", "❌ Close window from Taskbar",
    "🔍 Phóng to", "🔍 Zoom in",
    "🔍 Thu nhỏ", "🔍 Zoom out",
    "🔄 Chuyển cửa sổ tiếp theo", "🔄 Switch to next window",
    "🔄 Chuyển cửa sổ trước", "🔄 Switch to previous window",
    "🔄 Chuyển tab tiếp theo", "🔄 Switch to next tab",
    "🔄 Chuyển tab trước", "🔄 Switch to previous tab",
    "🔳 Đang chọn taskbar (phải)", "🔳 Selecting taskbar (right)",
    "🔳 Đang chọn taskbar (trái)", "🔳 Selecting taskbar (left)",
    "Preview", "Preview",
    
    ; ===== WELCOME SCREEN =====
    "👋 Chào mừng đến với FlowWheel", "👋 Welcome to FlowWheel",
    "Thao tác chuột mạnh mẽ cho Windows 10/11", "Powerful mouse gestures for Windows 10/11",
    "FlowWheel giúp chuột của bạn mạnh mẽ hơn với các cử chỉ thông minh, tăng tốc làm việc và điều khiển Windows dễ dàng.", "FlowWheel makes your mouse more powerful with smart gestures, speeding up work and making Windows control easier.",
    "⚠️ Yêu cầu phần cứng", "⚠️ Hardware requirement",
    "Cần chuột có 2 nút bên hông (XButton1/XButton2).", "Requires a mouse with 2 side buttons (XButton1/XButton2).",
    "🚀 Bắt đầu nhanh", "🚀 Quick start",
    "Hãy thử: Giữ CHUỘT PHẢI + cuộn để ", "Try: Hold RIGHT MOUSE + scroll to ",
    "chuyển tab trình duyệt", "switch browser tabs",
    "ngay!", "now!",
    "Nhấn Ctrl+Alt+H bất cứ lúc nào để xem hướng dẫn cử chỉ", "Press Ctrl+Alt+H anytime to view gesture guide",
    "🌐 Ngôn ngữ / Language:", "🌐 Language:",
    "Không hiển thị màn hình chào mừng này nữa", "Don't show this welcome screen again",
    "📖 Học cách dùng", "📖 Learn how to use",
    "✓ Bắt đầu sử dụng", "✓ Start using",
    
    ; ===== TRAY MENU =====
    "FlowWheel ", "FlowWheel ",
    "⚙️ Cài đặt`tCtrl+Alt+S", "⚙️ Settings`tCtrl+Alt+S",
    "📋 Tham khảo nhanh`tCtrl+Alt+H", "📋 Quick Reference`tCtrl+Alt+H",
    "📊 Thống kê", "📊 Statistics",
    "⏱️ Thời gian tiết kiệm : ", "⏱️ Time saved: ",
    "🎨 Phản hồi trực quan: ", "🎨 Visual feedback: ",
    "Bật", "On",
    "Tắt", "Off",
    "⏸️ Tạm dừng FlowWheel`tCtrl+Alt+P", "⏸️ Pause FlowWheel`tCtrl+Alt+P",
    "🔄 Tải lại script`tCtrl+Alt+R", "🔄 Reload script`tCtrl+Alt+R",
    "❌ Thoát`tCtrl+Alt+Q", "❌ Quit`tCtrl+Alt+Q",
    "✓ Đã bật phản hồi trực quan", "✓ Visual feedback enabled",
    "✗ Đã tắt phản hồi trực quan", "✗ Visual feedback disabled",
    "FlowWheel đang chạy ở khay hệ thống 🔔", "FlowWheel is running in system tray 🔔",
    "Nhấn vào mũi tên ^ ở khay hệ thống để xem biểu tượng", "Click the ^ arrow in system tray to see icon",
    
    ; ===== SUPPORT SYSTEM =====
    "Vui lòng nhập nội dung hoặc đính kèm file!", "Please enter content or attach a file!",
    "File quá lớn! Discord giới hạn 8MB", "File too large! Discord limit is 8MB",
    "(Chưa chọn file)", "(No file selected)",
    "✅ Đã chọn file: ", "✅ File selected: ",
    "🗑️ Đã xóa file đính kèm", "🗑️ Attachment cleared",
    "⚠️ FlowWheel vừa nhận phản hồi của bạn. Hãy đợi ", "⚠️ FlowWheel just received your feedback. Please wait ",
    " giây để gửi thêm", " seconds to send more",
    "Người dùng ẩn danh", "Anonymous user",
    "⏳ Đang gửi dữ liệu...", "⏳ Sending data...",
    "✅ Phản hồi của bạn đã được tiếp nhận. Chúng tôi trân trọng sự đóng góp này!", "✅ Your feedback has been received. We appreciate your contribution!",
    "💬 Cảm ơn bạn đã gửi phản hồi. Chúng tôi trân trọng sự đóng góp này !", "💬 Thank you for your feedback. We appreciate your contribution!",
    "⚠️ Không thể điều chỉnh độ sáng!", "⚠️ Cannot adjust brightness!",
    "⚠️ Chưa có dữ liệu để chia sẻ!", "⚠️ No data to share yet!",
    "Bạn có muốn chia sẻ thành tích", "Do you want to share achievements",
    " lên Discord không?", " to Discord?",
    "✅ Đã chia sẻ thành tích thành công!", "✅ Achievements shared successfully!",
    "⚠️ Không thể gửi: Mã lỗi", "⚠️ Cannot send: Error code",
    "⚠️ Không thể kết nối tới Discord!", "⚠️ Cannot connect to Discord!",
    
    ; ===== CONFIG EXPORT/IMPORT =====
    "Export FlowWheel Config", "Export FlowWheel Config",
    "✓ Config exported successfully!", "✓ Config exported successfully!",
    "Export failed: ", "Export failed: ",
    "Export Error", "Export Error",
    "Import FlowWheel Config", "Import FlowWheel Config",
    "This will overwrite your current settings. Continue?", "This will overwrite your current settings. Continue?",
    "Import Config", "Import Config",
    "✓ Config imported! Reloading...", "✓ Config imported! Reloading...",
    "Import failed: ", "Import failed: ",
    "Import Error", "Import Error",
    
    ; ===== ERROR MESSAGES =====
    "Error loading config", "Error loading config",
    "Config Error", "Config Error",
    "Error saving config", "Error saving config",
    
    ; ===== PAUSE/RESUME =====
    "⏸️ FlowWheel PAUSED`nPress Ctrl+Alt+P to resume", "⏸️ FlowWheel PAUSED`nPress Ctrl+Alt+P to resume",
    "▶️ FlowWheel RESUMED", "▶️ FlowWheel RESUMED"
)

; --- TIME FORMATTING FUNCTION ---
FormatTimeSaved(totalSeconds) {
    hours := Floor(totalSeconds / 3600)
    minutes := Floor(Mod(totalSeconds, 3600) / 60)
    seconds := Mod(totalSeconds, 60)
    if (hours > 0)
        return hours . "h " . minutes . "m " . seconds . "s"
    else if (minutes > 0)
        return minutes . "m " . seconds . "s"
    else
        return seconds . "s"
}